version: "3.8"

services:
  web:
    build: ./app
    ports:
      - 5000:5000
    develop:
      watch:
        # it'll watch for changes in package.json and package-lock.json and rebuild the container if there are any changes
        - path: ./app/requirements.txt
          action: rebuild
        - path: ./app
          target: /app
          action: sync


